apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ds-pipelines-viewercontroller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ds-pipelines-viewercontroller
    app.kubernetes.io/part-of: data-science-pipelines
  name: ds-pipelines-viewercontroller
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: ds-pipelines-viewercontroller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: ds-pipelines-viewercontroller
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-rmartine-tenant/data-science-pipelines/ds-pipelines-viewercontroller@sha256:3dad39a6609537c279f5f30230387da2eafce710fdffa0e3c481d36132465b23
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8888
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
