apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ds-pipelines-apiserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ds-pipelines-apiserver
    app.kubernetes.io/part-of: data-science-pipelines
  name: ds-pipelines-apiserver
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: ds-pipelines-apiserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: ds-pipelines-apiserver
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-rmartine-tenant/data-science-pipelines/ds-pipelines-apiserver@sha256:694cd335362c9b7b0b5acc99f60959aabebe169489232534f9638371cbb1fb19
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
