apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ds-pipelines-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ds-pipelines-operator
    app.kubernetes.io/part-of: data-science-pipelines
  name: ds-pipelines-operator
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: ds-pipelines-operator
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ds-pipelines-operator
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-rmartine-tenant/data-science-pipelines/ds-pipelines-operator@sha256:33e446475fcc131be18801ddd260f6b2c5ffb384bc7b301f79a2192df002f223
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
