apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: ds-pipelines-operator
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-rmartine-tenant/data-science-pipelines/ds-pipelines-operator@sha256:33e446475fcc131be18801ddd260f6b2c5ffb384bc7b301f79a2192df002f223
        name: container-image
        resources: {}
status: {}
