apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ds-pipelines-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ds-pipelines-operator
    app.kubernetes.io/part-of: data-science-pipelines
  name: ds-pipelines-operatorigjt
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: ds-pipelines-operator
    weight: 100
status: {}
