apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ds-pipelines-scheduledworkflow
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ds-pipelines-scheduledworkflow
    app.kubernetes.io/part-of: data-science-pipelines
  name: ds-pipelines-scheduledworkflow
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: ds-pipelines-scheduledworkflow
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: ds-pipelines-scheduledworkflow
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-rmartine-tenant/data-science-pipelines/ds-pipelines-scheduledworkflow@sha256:ac1b9c337f18d4d90ee7578e105016bb11ec2933145ca2a869f1abe1cb43c650
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
