apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ds-pipelines-scheduledworkflow
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ds-pipelines-scheduledworkflow
    app.kubernetes.io/part-of: data-science-pipelines
  name: ds-pipelines-scheduledworkflow
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ds-pipelines-scheduledworkflow
status:
  loadBalancer: {}
