apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ds-pipelines-apiserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ds-pipelines-apiserver
    app.kubernetes.io/part-of: data-science-pipelines
  name: ds-pipelines-apiserverbwpe
spec:
  path: /
  port:
    targetPort: 8080
  to:
    kind: Service
    name: ds-pipelines-apiserver
    weight: null
status: {}
