apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: data-science-pipelines
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-rmartine-tenant/data-science-pipelines/data-science-pipelines@sha256:1b7c0c1e4660a3940f34c446e38efade81b3385b1b060d1734289b65413e46ea
        name: my-go
        resources: {}
status: {}
